### ISSUE TITLE
Argument of type 'SPHttpClient' is not assignable to parameter of type 'SPHttpClient'.

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-webparts#594]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Authors
in /SharePoint/sp-dev-fx-webparts/tree/master/samples/react-list-form 

## Expected or Desired Behavior
gulp serve should finish then should show the workbench

## Observed Behavior

after npm install, 2 modules were missing so I ran:
npm install --save office-ui-fabric-react
npm install --save @microsoft/sp-http
then gulp serve show the errors:
[08:16:00] [typescript] TypeScript version: 2.4.2
[08:16:01] Finished subtask 'tslint' after 4.05 s
[08:16:04] Error - typescript - src\webparts\listForm\ListFormWebPart.ts(35,41): error TS2345: Argument of type 'SPHttpClient' is not assignable to parameter of type 'SPHttpClient'.
[08:16:04] Error - typescript - src\webparts\listForm\ListFormWebPart.ts(64,8): error TS2345: Argument of type '{ inDesignMode: boolean; spHttpClient: SPHttpClient; title: string; description: string; webUrl: ...' is not assignable to parameter of type 'Attributes & IListFormProps'.
[08:16:04] Error - typescript - src\webparts\listForm\components\formFields\FormField.tsx(12,30): error TS2307: Cannot find module 'office-ui-fabric-react/lib/components/TextField/TextField.scss'.
[08:16:04] Error - 'typescript' sub task errored after 4.54 s
 TypeScript error(s) occurred.

## Steps to Reproduce
Copy folder master/samples/react-list-form 
npm install
npm install --save office-ui-fabric-react
npm install --save @microsoft/sp-http
gulp serve 
## Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by kchiragowni** [comment]
@Ofer-Gal I had the same issue when I install packages (npm install) and run ran 'gulp serve'. 

However it worked for me when I run 'npm shrinkwrap' and 'npm install'

**Comment by ltabosa** [comment]
I'm having the same problem. The "npm shrinkwrap" didn't work for me. 
Someone else has another solution? Thank you

**Comment by waldekmastykarz** [comment]
Try running `npm dedupe`. I had the same issue after upgrading project from SPFx v1.4.1 to v1.6.0 and dedupe fixed it.

**Comment by ltabosa** [comment]
Thank you @waldekmastykarz. 
The solution uses SPFx v1.4.1, so I got to fix my @Microsoft/sp-http to the same version. 

I ran "npm install @microsoft/sp-http@1.4.1" and after "npm dedupe".

**Comment by FullStackRafik** [comment]
Hello,
I get always this error when I install a new package.
Any Solutions please?

**Comment by FullStackRafik** [comment]
Hello all,
I get resolved the issue, it's about the two packages @microsoft and @types.


Rafik
