### ISSUE TITLE
 React Content Query Online - Throws error on loading web part

### ISSUE THREAD

**Issue by maj-jacob** [pnp/sp-dev-fx-webparts#5349]
### Disclaimer

Yes

### Sample

https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-content-query-online

### Contributor(s)

@PopWarner @PaoloPia @hugoabernier

### What happened?

The web part does not work after put on page. It throws an "Something went wrong" error. Details only say [object Object]

![image](https://github.com/user-attachments/assets/f9864b71-b1a2-4e7f-882c-c225a127f411)

Maybe relevant: the build throws a warning:

![image](https://github.com/user-attachments/assets/b1578a71-354c-4629-a761-cd87d4f7f405)

(it's not a CDN issue as in other report suggested)

### Steps to reproduce

1. Build webpart
2. Add webpart to page

### Expected behavior

a working webpart, without an error

### Target SharePoint environment

SharePoint Online

### Developer environment

Windows

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [ ] Google Chrome
- [X] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### What version of Node.js is currently installed on your workstation?

v18.19.0

### What version of Node.js is required by the sample?

Node.js v16 | v18

### Paste the results of SPFx doctor

√ SharePoint Framework v1.18.2
√ Node v18.19.0
√ yo v5.0.0
√ gulp-cli v2.3.0
√ bundled typescript used
[
  {
    "check": "SharePoint Framework",
    "passed": true,
    "version": "1.18.2",
    "message": "SharePoint Framework v1.18.2 valid."
  },
  {
    "check": "SharePoint Framework",
    "passed": true,
    "version": "1.18.2",
    "message": "SharePoint Framework v1.18.2"
  },
  {
    "check": "Node",
    "passed": true,
    "message": "Node v18.19.0",
    "version": "18.19.0"
  },
  {
    "check": "yo",
    "passed": true,
    "message": "yo v5.0.0",
    "version": "5.0.0"
  },
  {
    "check": "gulp-cli",
    "passed": true,
    "message": "gulp-cli v2.3.0",
    "version": "2.3.0"
  },
  {
    "check": "typescript",
    "passed": true,
    "message": "bundled typescript used"
  }
]

**Comment by mauricework** [comment]
We are getting the same thing here as well.  I have been trying for couple of weeks to figure out what I was doing wrong since I am new to this lol.

**Comment by aliiamar** [comment]
> We are getting the same thing here as well. I have been trying for couple of weeks to figure out what I was doing wrong since I am new to this lol.

@mauricework is the issue still persisting in your environment? Do share any workarounds if you have :)

**Comment by mauricework** [comment]
@aliiamar nope it is still a problem.

**Comment by johndiehlwh** [comment]
Same issue here... did you find a solution yet?

**Comment by mauricework** [comment]
> Same issue here... did you find a solution yet?

Sorry no I have not.  I have not had a lot of time to look at it.

**Comment by raytri** [comment]
I am having this exact problem as well. Would really appreciate an answer, as we are trying to replace an older version of the webpart for security reasons.

**Comment by jleckard007** [comment]
I can't even get it to build I thought it needed Node v 10 to run but I can't get that version to run npm I am going to try another version.

**Comment by gdnhsg** [comment]
I have this problem, but put that down to MCAS breaking the expected URLs. This works fine without MCAS, however.

**Comment by mauricework** [comment]
@gdnhsg we are not using MCAS here so that should not be it.  When was the last time you built it do you know?

**Comment by jleckard007** [comment]
I would like it very much if someone could just put in the sspkg in the file I know a long time ago there was one pakage and it gave me this and several other webparts but I can't find that website anymore

**Comment by mauricework** [comment]
I believe I have found the issue (and thanks to one of my teammates - DL).  Once I had some time I put a bunch of logging in and finally got it to display this error

Cannot find manifest for 32b9363b-09ff-4959-929a-cab2663fb223_3.0.2. Store had [2.2.1]. Service worker version: (none); App version: (unknown); Next app version: (unknown)

That error is referencing the Microsoft Graph Toolkit (MGT) in the project.  In the package.json it is asking for this
    "@microsoft/microsoft-graph-client": "3.0.2",
But the tenant only has 2.2.1 of the MGT installed.  The fix I used was to do this in the project directory
npm i @microsoft/microsoft-graph-client@3.0.2 -SE

Example: C:\SPFX\sp-dev-fx-webparts\samples\react-content-query-online>npm i @microsoft/microsoft-graph-client@3.0.2 -SE

Once I did that and did a gulp clean and then did the build, bundle, and package everything worked.  I am not sure this is a great solution but it is the one that worked.  If anyone knows something better to do instead I can give it a try.

My thoughts are for those of us this is not working on we do not have MGT 3.0.2 installed in our tenant which is what is causing the issue.

Thanks.

**Comment by hugoabernier** [comment]
Great job finding this! I'll make a quick PR later to update this -- unless you would like to do it?

**Comment by mauricework** [comment]
Thanks.  Nope go ahead as I do not have a clue how to do that unless you have instructions.

**Comment by BenedictCard** [comment]
Hi guys. Any update on this. I've been trying to build and package this, but I'm getting the same result as well still. Been trying to resolve it with no luck yet

**Comment by maj-jacob** [comment]
> 
> Example: C:\SPFX\sp-dev-fx-webparts\samples\react-content-query-online>npm i @microsoft/microsoft-graph-client@3.0.2 -SE
> 

Thank you so much! That solved it!! 💯

**Comment by BenedictCard** [comment]
@maj-jacob  Hi man, what do you mean it's resolved? I'm still getting the same error

**Comment by BenedictCard** [comment]
@maj-jacob - I found it. I'm blind :)

**Comment by BenedictCard** [comment]
@maj-jacob is just running the npm install and then also running: npm i @microsoft/microsoft-graph-client@3.0.2 -SE ?

I did that and the build worked 100s, but still got the same warning on bundle --ship. The package-solution also was successful, but now I get an error:


Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
Technical Details
ERROR:
Cannot find module 'handlebars-helpers'

CALL STACK:
Error: Cannot find module 'handlebars-helpers'
    at https://ndalamoresources.sharepoint.com/sites/appcatalog/ClientSideAssets/00406271-0276-406f-9666-512623eb6709/content-query-web-part_9192421a2cd5145e8d22.js:2:1177156
    at new t (https://ndalamoresources.sharepoint.com/sites/appcatalog/ClientSideAssets/00406271-0276-406f-9666-512623eb6709/content-query-web-part_9192421a2cd5145e8d22.js:2:1177243)
    at gr (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:49347)
    at Go (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:68694)
    at Ks (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:111994)
    at wc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:98220)
    at Cc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:98148)
    at xc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:98011)
    at hc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:94998)
    at uc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:92354)

Is there something else that needs to be updated aswell, cos in the package-solution.json the IncludeClientSideAssets is set to true

**Comment by BenedictCard** [comment]
@maj-jacob is just running the npm install and then also running: npm i @microsoft/microsoft-graph-client@3.0.2 -SE ?

I did that and the build worked 100s, but still got the same warning on bundle --ship. The package-solution also was successful, but now I get an error:

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
Technical Details
ERROR:
Cannot find module 'handlebars-helpers'

CALL STACK:
Error: Cannot find module 'handlebars-helpers'
at https://xxxxxxxxxxxxxxxxxxxxxxxx/sites/appcatalog/ClientSideAssets/00406271-0276-406f-9666-512623eb6709/content-query-web-part_9192421a2cd5145e8d22.js:2:1177156
at new t (https://xxxxxxxxxxxxxxxxxxxxxxxx/sites/appcatalog/ClientSideAssets/00406271-0276-406f-9666-512623eb6709/content-query-web-part_9192421a2cd5145e8d22.js:2:1177243)
at gr (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:49347)
at Go (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:68694)
at Ks (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:111994)
at wc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:98220)
at Cc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:98148)
at xc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:98011)
at hc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:94998)
at uc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_0f19e982325997c8971e43a60d0a0c7e.js:101:92354)

Is there something else that needs to be updated aswell, cos in the package-solution.json the IncludeClientSideAssets is set to true

**Comment by BenedictCard** [comment]
Yay! I got it working after being a bit dumb. @maj-jacob thanks for pointing out the fix and @mauricework thank you for the solution. Nice work :)

**Comment by mauricework** [comment]
You are very welcome and yeah this does not get rid of the warning (at least not yet).  We would really like so see all the frameworks/addins or whatever you want to call them all updated as we noticed lots of security warnings in there and would like those all fixed up as well.  Not sure they are a big issue since we are in a MS tenant but would definitely like to see get them fixed up just in case.

**Comment by oermelie-prog** [comment]
in gulpfile.js

uncomment

    generatedConfiguration.module.rules.push(
      { test: /\.js$/, loader: 'unlazy-loader' }
    );

run npm i unlazy-loader in project folder

also run the fix with

npm i @microsoft/microsoft-graph-client@3.0.2 -SE

does the trick for me

**Comment by satya068** [comment]
Hi I have managed to solve the issue using the below 
1) locate the code through vscode 
\your folder directory\src\webparts\contentQuery\components\contentQuery.tsx  
 _let helpers = require<any>('handlebars-helpers')({
      handlebars: Handlebars
    });_
**comment out the above 3 lines**
2) run npm i unlazy-loader in project folder
3) run npm i @microsoft/microsoft-graph-client@3.0.2 -SE
4)gulp clean
5)gulp build
6)gulp bundle --ship
7)gulp package-solution --ship

**Comment by gvijaikumar9** [comment]
The workarounds above fix it (the old sample's handlebars-helpers / graph-client deps). If anyone would rather not patch it, I built a maintained, dependency-light SPFx content/news rollup, point it at a list or fall back to Microsoft Search, no CQWP config:

Repo: https://github.com/gvijaikumar9/SPFx-Intranet-Suite
Details: https://www.fivenumber.com/a-content-rollup-web-part-for-sharepoint-news/
It's a simple, reliable rollup, not a full CQWP replacement (no granular filtering/templating). Hope it helps.
